[toolchain]
anchor_version = "0.31.1"
solana_version = "2.2.20"

[features]
resolution = false
skip-lint = false

[programs.localnet]
oft = "J74cB1YqpYQZooGxUiV5uUCfa2hD34SGLCVW4J4ZXe3h"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./junk-id.json"

[scripts]
test = "npx jest test/anchor"
